version: "3"

services:
  nginx:
    image: nginx:1-alpine
    env_file: .env
    depends_on:
      - php
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html:rw,delegated
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    working_dir: /var/www/html/
    tty: true

  php:
    build: docker/php
    env_file: .env
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - .:/var/www/html:rw,delegated
      - ./docker/php/conf.d/custom.ini:/usr/local/etc/php/conf.d/custom.ini:ro
    tty: true

  postgres:
    image: postgres:10-alpine
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    tty: true

volumes:
  postgres: {}
